<?

require_once("library/Boot_Session.php");

$dbCmd = new DbCmd();

set_time_limit(50000);
/*
$searchReplaceArr = array(
"g-all-bc-3-general"=>"g-all-3-pm-bc_general",
"g-all-bc-3-ExactMatchBusinessCards"=>"g-all-3-em-bc_general",
"g-all-bc-3-mispellings"=>"g-all-3-pm-bc_mispellings",
"g-all-bc-3-mispellings"=>"g-all-3-pm-bc_misspell",
"g-all-bc-3-design"=>"g-all-3-pm-bc_design",
"g-all-bc-3-make"=>"g-all-3-pm-bc_make",
"g-all-bc-3-online"=>"g-all-3-pm-bc_make",
"g-all-bc-3-quality"=>"g-all-3-pm-bc_quality",
"g-all-bc-3-industry-hairdresser"=>"g-all-3-pm-bc_ind_Hair",
"g-all-bc-3-custom"=>"g-all-3-pm-bc_custom",
"g-all-bc-3-glossy"=>"g-all-3-pm-bc_glossy",
"g-all-bc-3-free"=>"g-all-3-pm-bc_free",
"g-all-bc-3-create"=>"g-all-3-pm-bc_create",
"g-all-bc-3-industry-cleaning"=>"g-all-3-pm-bc_ind_Clean",
"g-all-bc-3-printing"=>"g-all-3-pm-bc_printing",
"g-all-bc-3-industry-realtor"=>"g-all-3-pm-bc_ind_Realty",
"g-all-bc-3-industry-animal"=>"g-all-3-pm-bc_ind_Animal",
"g-all-bc-3-cheap"=>"g-all-3-pm-bc_cheap",
"g-all-bc-3-personal"=>"g-all-3-pm-bc_personal",
"g-all-bc-3-industry-gardening"=>"g-all-3-pm-bc_ind_Garden",
"g-all-bc-3-calendar"=>"g-all-3-pm-bc_calendar",
"g-all-bc-3-unique"=>"g-all-3-pm-bc_unique",
"g-all-bc-3-color"=>"g-all-3-pm-bc_color",
"g-all-bc-3-industry-fashion"=>"g-all-3-pm-bc_ind_Fashion",
"g-all-bc-3-appointment"=>"g-all-3-pm-bc_appointment",
"g-all-bc-3-industry-beauty"=>"g-all-3-pm-bc_ind_Beauty",

"gcn-all-bc-3-templates"=>"gcn-all-3-pm-bc_template",
"gcn-all-bc-3-create"=>"gcn-all-3-pm-bc_create",
"gcn-all-bc-3-general"=>"gcn-all-3-pm-bc_general",
"gcn-all-bc-3-design"=>"gcn-all-3-pm-bc_design",
"gcn-all-bc-3-selfdesigned"=>"gcn-all-3-pm-bc_selfdesigned",

"gcn-geo-CALosAngeles-bc-3-templates"=>"gcn-geo_bCty_Z2-3-pm-bc_template",
"gcn-geo-CALosAngeles-bc-3-create"=>"gcn-geo_bCty_Z2-3-pm-bc_create",
"gcn-geo-CALosAngeles-bc-3-general"=>"gcn-geo_bCty_Z2-3-pm-bc_general",
"gcn-geo-CALosAngeles-bc-3-design"=>"gcn-geo_bCty_Z2-3-pm-bc_design",
"gcn-geo-CALosAngeles-bc-3-selfdesigned"=>"gcn-geo_bCty_Z2-3-pm-bc_selfdesigned",

"g-all-lh-general"=>"g-all-1-pm-lh_general",

"g-all-pme-general"=>"g-all-1-pm-pme_general",

"g-all-pc-create"=>"g-all-1-pm-pc_create",
"g-all-pc-design"=>"g-all-1-pm-pc_design",
"g-all-pc-personal"=>"g-all-1-pm-pc_personal",
"g-all-pc-photo"=>"g-all-1-pm-pc_photo",
"g-all-pc-realestate"=>"g-all-1-pm-pc_ind_Realty",
"g-all-pc-printing"=>"g-all-1-pm-pc_printing",
"g-all-pc-custom"=>"g-all-1-pm-pc_custom",
"g-all-pc-cheap"=>"g-all-1-pm-pc_cheap",
"g-all-pc-general"=>"g-all-1-pm-pc_general",
"g-all-pc-make"=>"g-all-1-pm-pc_make",
"g-all-pc-std"=>"g-all-1-pm-pc_savethedate",
"gcn-all-pc-personal"=>"gcn-all-1-pm-pc_personal",
"gcn-all-pc-photo"=>"gcn-all-1-pm-pc_photo",
"gcn-all-pc-realestate"=>"gcn-all-1-pm-pc_ind_Realty",
"gcn-all-pc-custom"=>"gcn-all-1-pm-pc_custom",
"gcn-all-pc-general"=>"gcn-all-1-pm-pc_general",

"gcn-CALosAngeles-pc-personal"=>"gcn-geo_bCty_Z2-1-pm-pc_personal",
"gcn-CALosAngeles-pc-photo"=>"gcn-geo_bCty_Z2-1-pm-pc_photo",
"gcn-CALosAngeles-pc-realestate"=>"gcn-geo_bCty_Z2-1-pm-pc_ind_Realty",
"gcn-CALosAngeles-pc-custom"=>"gcn-geo_bCty_Z2-1-pm-pc_custom",
"gcn-CALosAngeles-pc-general"=>"gcn-geo_bCty_Z2-1-pm-pc_general",


"g-CALosAngeles-pc-printing"=>"g-geo_bCty_Z2-1-pm-pc_printing",
"g-CALosAngeles-pc-make"=>"g-geo_bCty_Z2-1-pm-pc_make",
"g-CALosAngeles-pc-std"=>"g-geo_bCty_Z2-1-pm-pc_savethedate",
"g-CALosAngeles-pc-personal"=>"g-geo_bCty_Z2-1-pm-pc_personal",
"g-CALosAngeles-pc-photo"=>"g-geo_bCty_Z2-1-pm-pc_photo",
"g-CALosAngeles-pc-general"=>"g-geo_bCty_Z2-1-pm-pc_general",
"g-CALosAngeles-pc-custom"=>"g-geo_bCty_Z2-1-pm-pc_custom",
"g-CALosAngeles-pc-design"=>"g-geo_bCty_Z2-1-pm-pc_design",
"g-CALosAngeles-pc-create"=>"g-geo_bCty_Z2-1-pm-pc_create",
"g-CALosAngeles-pc-cheap"=>"g-geo_bCty_Z2-1-pm-pc_cheap",
"g-CALosAngeles-pc-ExactMatchPostcards"=>"g-geo_bCty_Z2-1-em-pc_general",


"g-CALosAngeles-bc-3-general"=>"g-geo_bCty_Z2-3-pm-bc_general",
"g-CALosAngeles-bc-3-mispellings"=>"g-geo_bCty_Z2-3-pm-bc_misspell",
"g-CALosAngeles-bc-3-online"=>"g-geo_bCty_Z2-3-pm-bc_online",
"g-CALosAngeles-bc-3-color"=>"g-geo_bCty_Z2-3-pm-bc_color",
"g-CALosAngeles-bc-3-printing"=>"g-geo_bCty_Z2-3-pm-bc_printing",
"g-CALosAngeles-bc-3-industry-cleaning"=>"g-geo_bCty_Z2-3-pm-bc_ind_Clean",
"g-CALosAngeles-bc-3-industry-gardening"=>"g-geo_bCty_Z2-3-pm-bc_ind_Garden",
"g-CALosAngeles-bc-3-industry-beauty"=>"g-geo_bCty_Z2-3-pm-bc_ind_Beauty",
"g-CALosAngeles-bc-3-industry-hairdresser"=>"g-geo_bCty_Z2-3-pm-bc_ind_Hair",
"g-CALosAngeles-bc-3-unique"=>"g-geo_bCty_Z2-3-pm-bc_unique",
"g-CALosAngeles-bc-3-create"=>"g-geo_bCty_Z2-3-pm-bc_create",
"g-CALosAngeles-bc-3-calendar"=>"g-geo_bCty_Z2-3-pm-bc_calendar",
"g-CALosAngeles-bc-3-cheap"=>"g-geo_bCty_Z2-3-pm-bc_cheap",
"g-CALosAngeles-bc-3-industry-fashion"=>"g-geo_bCty_Z2-3-pm-bc_ind_Fashion",
"g-CALosAngeles-bc-3-free"=>"g-geo_bCty_Z2-3-pm-bc_free",
"g-CALosAngeles-bc-3-quality"=>"g-geo_bCty_Z2-3-pm-bc_quality",
"g-CALosAngeles-bc-3-make"=>"g-geo_bCty_Z2-3-pm-bc_make",
"g-CALosAngeles-bc-3-glossy"=>"g-geo_bCty_Z2-3-pm-bc_glossy",
"g-CALosAngeles-bc-3-order"=>"g-geo_bCty_Z2-3-pm-bc_order",
"g-CALosAngeles-bc-3-personal"=>"g-geo_bCty_Z2-3-pm-bc_personal",
"g-CALosAngeles-bc-3-appointment"=>"g-geo_bCty_Z2-3-pm-bc_appointment",
"g-CALosAngeles-bc-3-design"=>"g-geo_bCty_Z2-3-pm-bc_design",
"g-CALosAngeles-bc-3-industry-realtor"=>"g-geo_bCty_Z2-3-pm-bc_ind_Realty",
"g-CALosAngeles-bc-3-industry-animal"=>"g-geo_bCty_Z2-3-pm-bc_ind_Animal",
"g-CALosAngeles-bc-3-custom"=>"g-geo_bCty_Z2-3-pm-bc_custom",


"g-CALosAngeles-pme-general"=>"g-geo_bCty_Z2-1-pm-pme_general",


"g-country-pc-custom-m_custompost_cards"=>"g-all-1-pm-pc_custom",

"g-all-1-em-pme-generalg-all-1-em-pme-general"=>"g-all-1-em-pme_general",
"g-all-1-em-pme-generalg-all-1-em-pme_general"=>"g-all-1-em-pme_general",
"g-country-pme-BC"=>"g-all-1-pm-pme_general",
"g-country-pme-PC"=>"g-all-1-pm-pme_general",
"g-country-pme-BC"=>"g-all-1-pm-pme_general",


"g-all-bc-3-general"=>"g-all-3-pm-bc_general"

);




foreach($searchReplaceArr as $thisSearchPhrase => $thisReplacePhrase){
	
	$tableStr = "<table width='1000'>";
	$dbCmd->UpdateQuery("bannerlog", array("Name"=>$thisReplacePhrase), "Name LIKE '" . DbCmd::EscapeSQL($thisSearchPhrase) . "'");
	$dbCmd->UpdateQuery("orders", array("Referral"=>$thisReplacePhrase), "Referral LIKE '" . DbCmd::EscapeSQL($thisSearchPhrase) . "'");
	usleep(400000);
	
	$tableStr .= "<tr><td width='500'>" . $thisSearchPhrase . "</td><td>" . $thisReplacePhrase . "</td></tr>\n";
	$tableStr .= "</table>";
	print $tableStr;
	flush();
}
*/
print '<hr>';


// ---------------------------------   Done with Manual Search and Replaces ------------------------------------
$dbCmd->Query("SELECT DISTINCT Name FROM bannerlog WHERE (Name LIKE 'g-%' OR Name LIKE 'gnc-%') AND (Name NOT LIKE 'g%-geo%' AND Name NOT LIKE 'g%-all%' AND Name NOT LIKE '%-comp-%' AND Name NOT LIKE '%.html%' AND Name NOT LIKE '%.php%')");
$fixTheseTrackingCodesArr = $dbCmd->GetValueArr();

foreach($fixTheseTrackingCodesArr as $thisBannerCode){
	print $thisBannerCode . "<br>";
}



$fixTheseTrackingCodesArr = array(
'g-bc-3-general-pm_businesscard_Eastern_State-Florida',
'g-bc-3-industry-hairdresser-em_hairstylistBCs_Central_Cty-Austin',
'g-bc-3-general-pm_businesscards_Pacific_Cty-LosAngeles',
'g-bc-3-general-pm_businesscards_Eastern_Cty-NYC',
'g-bc-3-industry-antiques-pm_antiquesBC_Pacific_Cty-Lancaster',
'g-bc-3-industry-computerrepair-pm_computerrepairBC_Eastern_Cty-Miami',
'g-bc-3-industry-locksmith-pm_locksmithBCs_Pacific_Cty-Fresno',
'g-bc-3-industry-wine-pm_wineryBCs_Eastern_State-Michigan',
'g-bc-3-industry-writing-em_BCsforwriters',
'g-bc-3-make-pm_makebusinesscard'
);




print "<hr>";



foreach($fixTheseTrackingCodesArr as $thisCodeToFix){
	
	$tableStr = "<table width='1000'>";
	
	$newTrackingCode = createFinalTrackingCodeFromTokenizedString($thisCodeToFix, getIndustryCodeReplacement(getLocationCodeReplacement($thisCodeToFix)));
	$dbCmd->UpdateQuery("bannerlog", array("Name"=>$newTrackingCode), "Name LIKE '" . DbCmd::EscapeLikeQuery($thisCodeToFix) . "'");
	$dbCmd->UpdateQuery("orders", array("Referral"=>$newTrackingCode), "Referral LIKE '" . DbCmd::EscapeLikeQuery($thisCodeToFix) . "'");
	usleep(40000);
	
	$tableStr .= "<tr><td width='500'>" . $thisCodeToFix . "</td><td>" . $newTrackingCode . "</td></tr>\n";
	
	$tableStr .= "</table>";
	print $tableStr;
	flush();
}

print "<hr>Done<hr>";


function createFinalTrackingCodeFromTokenizedString($originalCode, $tokenizedCode){
	
	$matches = array();
	
	// make sure we are only fixing google codes.
	if(!preg_match("/^(g(cn)?)\-/", $originalCode, $matches)){
print "<br><br>No Origin Prefix Found";
		return $originalCode;
	}
	
	$bannerOrigin = $matches[1];

	
	// Get the Match Type (phrase match, broad match, or exact).
	if(!preg_match("/\-((em|bm|pm|m))_/", $originalCode, $matches)){
print "<br><br>No Match Type Found";
		return $originalCode;
	}
	
	$matchType = $matches[1];
	
	// correct an error by Brooke.
	if($matchType == "m")
		$matchType = "pm";

	
	// If we can't match the industry, then return the original code.
	if(!preg_match("/!(\w+)!/", $tokenizedCode, $matches)){
print "<br><br>No Industry Token";
		return $originalCode;
	}
	
	$industryCode = $matches[1];
	
	
	// If we can't geo Location, then return the original code.
	if(!preg_match("/\^(\w+)\^/", $tokenizedCode, $matches)){
print "<br><br>No Location Token";
		return $originalCode;
	}
	
	$geoLocationCode = $matches[1];
	
	//g-geo_bCty_Z2-3-em-bc_ind_Beauty
	if(preg_match("/-bc-/", $originalCode)){
		$newTrackingCode = $bannerOrigin . "-" . $geoLocationCode . "-3-" . $matchType . "-" . $industryCode;
		return $newTrackingCode;
	}
	else if(preg_match("/-pc-/", $originalCode)){
		$newTrackingCode = $bannerOrigin . "-" . $geoLocationCode . "-1-" . $matchType . "-" . $industryCode;
		return $newTrackingCode;
	}
	else if(preg_match("/-gc-/", $originalCode) && preg_match("/std/", $originalCode)){
		$newTrackingCode = $bannerOrigin . "-" . $geoLocationCode . "-1-" . $matchType . "-" . $industryCode;
		return $newTrackingCode;
	}
	
print "<br><br>No Product identifier Found";	
	return $originalCode;
}
	

function getIndustryCodeReplacement($trackingCodeStr){
	
	
	$bizCardIndustrySearchArr = array(
	'APPOINTMENT' => 'bc_appointment',
	'APPOINTMENT' => 'appointment',
	'CALENDAR' => 'bc_calendar',
	'CALENDAR' => 'calendar',
	'CHEAP' => 'bc_cheap',
	'COUPON' => 'bc_coupon',
	'COLOR' => 'bc_color',
	'CREATE' => 'bc_create',
	'CUSTOM' => 'bc_custom',
	'DESIGN' => 'bc_design',
	'FREE' => 'bc_free',
	'GENERAL' => 'bc_general',
	'GLOSSY' => 'bc_glossy',
	'INDUSTRY-ACADEMIC' => 'bc_ind_Misc',
	'INDUSTRY-ACCOUNTING' => 'bc_ind_Misc',
	'INDUSTRY-ANIMAL' => 'bc_ind_Animal',
	'INDUSTRY-ARCHITECT' => 'bc_ind_Misc',
	'INDUSTRY-AUTO' => 'bc_ind_Misc',
	'INDUSTRY-AVIATION' => 'bc_ind_Misc',
	'INDUSTRY-BABYSITTING' => 'bc_ind_Misc',
	'INDUSTRY-BAKING' => 'bc_ind_Misc',
	'INDUSTRY-BEAUTY' => 'bc_ind_Beauty',
	'INDUSTRY-BRICK' => 'bc_ind_Misc',
	'INDUSTRY-BUILDER' => 'bc_ind_Misc',
	'INDUSTRY-CAFE' => 'bc_ind_Misc',
	'INDUSTRY-CARPENTER' => 'bc_ind_Misc',
	'INDUSTRY-CHIROPRACTOR' => 'bc_ind_Misc',
	'INDUSTRY-CLEANING' => 'bc_ind_Clean',
	'INDUSTRY-ANTIQUES' => 'bc_ind_Misc',
	'INDUSTRY-bookkeeping' => 'bc_ind_Misc',
	'INDUSTRY-cameraman' => 'bc_ind_Misc',
	'INDUSTRY-mortgage' => 'bc_ind_Misc',
	'INDUSTRY-baby' => 'bc_ind_Misc',
	'INDUSTRY-computersales' => 'bc_ind_Misc',
	'INDUSTRY-cosmetics' => 'bc_ind_Misc',
	'INDUSTRY-drycleaner' => 'bc_ind_Misc',
	'INDUSTRY-filmmaking' => 'bc_ind_Misc',
	'INDUSTRY-gift' => 'bc_ind_Misc',
	'INDUSTRY-humanresouces' => 'bc_ind_Misc',
	'INDUSTRY-COMPUTERREPAIR' => 'bc_ind_Misc',
	'INDUSTRY-LOCKSMITH' => 'bc_ind_Misc',
	'INDUSTRY-CONSULTANT' => 'bc_ind_Misc',
	'INDUSTRY-mechanic' => 'bc_ind_Misc',
	'INDUSTRY-military' => 'bc_ind_Misc',
	'INDUSTRY-moving' => 'bc_ind_Misc',
	'INDUSTRY-nautical' => 'bc_ind_Misc',
	'INDUSTRY-waitstaff' => 'bc_ind_Misc',
	'INDUSTRY-notary' => 'bc_ind_Misc',
	'INDUSTRY-painting' => 'bc_ind_Misc',
	'INDUSTRY-photography' => 'bc_ind_Misc',
	'INDUSTRY-wine' => 'bc_ind_Misc',
	'INDUSTRY-writing' => 'bc_ind_Misc',
	'INDUSTRY-scubadiving' => 'bc_ind_Misc',
	'INDUSTRY-sports' => 'bc_ind_Misc',
	'INDUSTRY-COUNSELING' => 'bc_ind_Misc',
	'INDUSTRY-DENTAL' => 'bc_ind_Misc',
	'INDUSTRY-ELECTRICAL' => 'bc_ind_Misc',
	'INDUSTRY-ELECTRONICS' => 'bc_ind_Misc',
	'INDUSTRY-FARMING' => 'bc_ind_Misc',
	'INDUSTRY-FASHION' => 'bc_ind_Fashion',
	'INDUSTRY-FENCEBUILDING' => 'bc_ind_Misc',
	'INDUSTRY-FINANCIAL' => 'bc_ind_Misc',
	'INDUSTRY-FITNESS' => 'bc_ind_Misc',
	'INDUSTRY-FLORIST' => 'bc_ind_Misc',
	'INDUSTRY-FURNITURE' => 'bc_ind_Misc',
	'INDUSTRY-grocery' => 'bc_ind_Misc',
	'INDUSTRY-GARDENING' => 'bc_ind_Garden',
	'INDUSTRY-HAIRDRESSER' => 'bc_ind_Hair',
	'INDUSTRY-HEALTHCARE' => 'bc_ind_Misc',
	'INDUSTRY-INSURANCE' => 'bc_ind_Misc',
	'INDUSTRY-INTERIORDESIGN' => 'bc_ind_Misc',
	'INDUSTRY-IRONWORKS' => 'bc_ind_Misc',
	'INDUSTRY-IT' => 'bc_ind_Misc',
	'INDUSTRY-LAW' => 'bc_ind_Misc',
	'INDUSTRY-MASSAGE' => 'bc_ind_Misc',
	'INDUSTRY-MECHANIC' => 'bc_ind_Misc',
	'INDUSTRY-MILITARY' => 'bc_ind_Misc',
	'INDUSTRY-MUSIC' => 'bc_ind_Misc',
	'INDUSTRY-NAUTICAL' => 'bc_ind_Misc',
	'INDUSTRY-NOTARY' => 'bc_ind_Misc',
	'INDUSTRY-PARTY' => 'bc_ind_Misc',
	'INDUSTRY-PHOTOGRAPHY' => 'bc_ind_Misc',
	'INDUSTRY-PLUMBING' => 'bc_ind_Misc',
	'INDUSTRY-REALTOR' => 'bc_ind_Realty',
	'REALTOR' => 'bc_ind_Realty',
	'INDUSTRY-SECRETARY' => 'bc_ind_Misc',
	'INDUSTRY-SPORTS' => 'bc_ind_Misc',
	'INDUSTRY-STUDENT' => 'bc_ind_Misc',
	'INDUSTRY-TAILOR' => 'bc_ind_Misc',
	'INDUSTRY-TAXI' => 'bc_ind_Misc',
	'INDUSTRY-TRAVEL' => 'bc_ind_Misc',
	'INDUSTRY-TUTOR' => 'bc_ind_Misc',
	'INDUSTRY-VET' => 'bc_ind_Misc',
	'INDUSTRY-WRITING' => 'bc_ind_Misc',
	'MAKE' => 'bc_make',
	'MISPELLINGS' => 'bc_misspell',
	'ONLINE' => 'bc_online',
	'ORDER' => 'bc_order',
	'PERSONAL' => 'bc_personal',
	'PME' => 'pme_general',
	'PRINTING' => 'bc_printing',
	'PROFESSIONAL' => 'bc_quality',
	'QUALITY' => 'bc_quality',
	'UNIQUE' => 'bc_unique'
	);
	
	
	
	
	$postCardIndustrySearchArr = array(
	'APPOINTMENT' => 'pc_appointment',
	'CALENDAR' => 'pc_calendar',
	'CHEAP' => 'pc_cheap',
	'COLOR' => 'pc_color',
	'CREATE' => 'pc_create',
	'VARIABLEDATA' => 'pc_vardata',
	'CUSTOM' => 'pc_custom',
	'DESIGN' => 'pc_design',
	'FREE' => 'pc_free',
	'GENERAL' => 'pc_general',
	'GLOSSY' => 'pc_glossy',
	'INDUSTRY-ACADEMIC' => 'pc_ind_Misc',
	'INDUSTRY-ACCOUNTING' => 'pc_ind_Misc',
	'INDUSTRY-ANIMAL' => 'pc_ind_Animal',
	'INDUSTRY-ARCHITECT' => 'pc_ind_Misc',
	'INDUSTRY-ANTIQUES' => 'pc_ind_Misc',
	'INDUSTRY-COMPUTERREPAIR' => 'pc_ind_Misc',
	'INDUSTRY-LOCKSMITH' => 'pc_ind_Misc',
	'INDUSTRY-AUTO' => 'pc_ind_Misc',
	'INDUSTRY-AVIATION' => 'pc_ind_Misc',
	'INDUSTRY-BABYSITTING' => 'pc_ind_Misc',
	'INDUSTRY-BAKING' => 'pc_ind_Misc',
	'INDUSTRY-BEAUTY' => 'pc_ind_Beauty',
	'INDUSTRY-COSMETICS' => 'pc_ind_Beauty',
	'INDUSTRY-BRICK' => 'pc_ind_Misc',
	'INDUSTRY-STUDENT' => 'pc_ind_Misc',
	'INDUSTRY-TAXI' => 'pc_ind_Misc',
	'INDUSTRY-TRAVEL' => 'pc_ind_Misc',
	'INDUSTRY-TUTOR' => 'pc_ind_Misc',
	'INDUSTRY-WINE' => 'pc_ind_Misc',
	'INDUSTRY-WRITING' => 'pc_ind_Misc',
	'INDUSTRY-COSMETICS' => 'pc_ind_Misc',
	'INDUSTRY-FITNESS' => 'pc_ind_Misc',
	'INDUSTRY-FINANCIAL' => 'pc_ind_Misc',
	'INDUSTRY-FLORIST' => 'pc_ind_Misc',
	'INDUSTRY-HEALTHCARE' => 'pc_ind_Misc',
	'INDUSTRY-PLUMBING' => 'pc_ind_Misc',
	'INDUSTRY-DENTAL' => 'pc_ind_Misc',
	'INDUSTRY-DRYCLEANER' => 'pc_ind_Misc',
	'INDUSTRY-ELECTRICAL' => 'pc_ind_Misc',
	'INDUSTRY-ELECTRICAL' => 'pc_ind_Misc',
	'INDUSTRY-CHIROPRACTOR' => 'pc_ind_Misc',
	'INDUSTRY-BUILDER' => 'pc_ind_Misc',
	'INDUSTRY-CAFE' => 'pc_ind_Misc',
	'INDUSTRY-CARPENTER' => 'pc_ind_Misc',
	'INDUSTRY-CHIROPRACTOR' => 'pc_ind_Misc',
	'INDUSTRY-CLEANING' => 'pc_ind_Clean',
	'INDUSTRY-CLEANING' => 'pc_ind_Clean',
	'INDUSTRY-CONSULTANT' => 'pc_ind_Misc',
	'INDUSTRY-COUNSELING' => 'pc_ind_Misc',
	'INDUSTRY-DENTAL' => 'pc_ind_Misc',
	'INDUSTRY-ELECTRICAL' => 'pc_ind_Misc',
	'INDUSTRY-ELECTRONICS' => 'pc_ind_Misc',
	'INDUSTRY-FARMING' => 'pc_ind_Misc',
	'INDUSTRY-LOCKSMITH' => 'pc_ind_Misc',
	'INDUSTRY-MASSAGE' => 'pc_ind_Misc',
	'INDUSTRY-HUMANRESOUCES' => 'pc_ind_Misc',
	'INDUSTRY-MILITARY' => 'pc_ind_Misc',
	'INDUSTRY-MOVING' => 'pc_ind_Misc',
	'INDUSTRY-MUSIC' => 'pc_ind_Misc',
	'INDUSTRY-NAUTICAL' => 'pc_ind_Misc',
	'INDUSTRY-NOTARY' => 'pc_ind_Misc',
	'INDUSTRY-PAINTING' => 'pc_ind_Misc',
	'INDUSTRY-PARTY' => 'pc_ind_Misc',
	'INDUSTRY-PHOTOGRAPHY' => 'pc_ind_Misc',
	'INDUSTRY-INTERIORDESIGN' => 'pc_ind_Misc',
	'INDUSTRY-IRONWORKS' => 'pc_ind_Misc',
	'INDUSTRY-LAW' => 'pc_ind_Misc',
	'INDUSTRY-FASHION' => 'pc_ind_Fashion',
	'INDUSTRY-FENCEBUILDING' => 'pc_ind_Misc',
	'INDUSTRY-FINANCIAL' => 'pc_ind_Misc',
	'INDUSTRY-FITNESS' => 'pc_ind_Misc',
	'INDUSTRY-FLORIST' => 'pc_ind_Misc',
	'INDUSTRY-COMPUTER' => 'pc_ind_Misc',
	'INDUSTRY-CONSULTANT' => 'pc_ind_Misc',
	'INDUSTRY-FURNITURE' => 'pc_ind_Misc',
	'INDUSTRY-GARDENING' => 'pc_ind_Garden',
	'INDUSTRY-HAIRDRESSER' => 'pc_ind_Hair',
	'INDUSTRY-HEALTHCARE' => 'pc_ind_Misc',
	'INDUSTRY-INSURANCE' => 'pc_ind_Misc',
	'INDUSTRY-INTERIORDESIGN' => 'pc_ind_Misc',
	'INDUSTRY-IRONWORKS' => 'pc_ind_Misc',
	'INDUSTRY-IT' => 'pc_ind_Misc',
	'INDUSTRY-LAW' => 'pc_ind_Misc',
	'INDUSTRY-MASSAGE' => 'pc_ind_Misc',
	'INDUSTRY-MECHANIC' => 'pc_ind_Misc',
	'INDUSTRY-MILITARY' => 'pc_ind_Misc',
	'INDUSTRY-MUSIC' => 'pc_ind_Misc',
	'INDUSTRY-NAUTICAL' => 'pc_ind_Misc',
	'INDUSTRY-NOTARY' => 'pc_ind_Misc',
	'INDUSTRY-PARTY' => 'pc_ind_Misc',
	'INDUSTRY-PHOTOGRAPHY' => 'pc_ind_Misc',
	'INDUSTRY-PLUMBING' => 'pc_ind_Misc',
	'INDUSTRY-REALTOR' => 'pc_ind_Realty',
	'REALESTATE' => 'pc_ind_Realty',
	'MORTGAGE' => 'pc_ind_Realty',
	'INDUSTRY-SECRETARY' => 'pc_ind_Misc',
	'INDUSTRY-SPORTS' => 'pc_ind_Misc',
	'INDUSTRY-STUDENT' => 'pc_ind_Misc',
	'INDUSTRY-TAILOR' => 'pc_ind_Misc',
	'INDUSTRY-TAXI' => 'pc_ind_Misc',
	'INDUSTRY-TRAVEL' => 'pc_ind_Misc',
	'INDUSTRY-TUTOR' => 'pc_ind_Misc',
	'INDUSTRY-VET' => 'pc_ind_Misc',
	'INDUSTRY-WRITING' => 'pc_ind_Misc',
	'MAKE' => 'pc_make',
	'MISPELLINGS' => 'pc_misspell',
	'ONLINE' => 'pc_online',
	'ORDER' => 'pc_order',
	'PERSONAL' => 'pc_personal',
	'PME' => 'pme_general',
	'PRINTING' => 'pc_printing',
	'PROFESSIONAL' => 'pc_quality',
	'QUALITY' => 'pc_quality',
	'STD' => 'pc_savethedate',
	'SAVE' => 'pc_savethedate',
	'PHOTO' => 'pc_photo',
	'UNIQUE' => 'pc_unique'
	);
	
	
	
	
	if(preg_match("/\-bc\-/", $trackingCodeStr)){

		foreach($bizCardIndustrySearchArr as $thisBizCodeIndustSearch => $thisBizCodeIndReplace){
			
			if(preg_match("/$thisBizCodeIndustSearch/i", $trackingCodeStr)){
			
				$trackingCodeStr = preg_replace("/$thisBizCodeIndustSearch/i", ("!" . $thisBizCodeIndReplace . "!"), $trackingCodeStr, 1);
				return $trackingCodeStr;
			}
		}
	}
	
	if(preg_match("/\-pc\-/", $trackingCodeStr) || (preg_match("/\-gc\-/", $trackingCodeStr) && preg_match("/std/", $trackingCodeStr))){

		foreach($postCardIndustrySearchArr as $thisPostCodeIndustSearch => $thisPostCodeIndReplace){
			
			if(preg_match("/$thisPostCodeIndustSearch/i", $trackingCodeStr)){
			
				$trackingCodeStr = preg_replace("/$thisPostCodeIndustSearch/i", ("!" . $thisPostCodeIndReplace . "!"), $trackingCodeStr, 1);
				return $trackingCodeStr;
			}
		}
	}
	
	print "<br><br>No Product Name Found or industry matched ($trackingCodeStr)";
	
	return $trackingCodeStr;
}


function getLocationCodeReplacement($trackingCodeStr){
	
	if(preg_match("/\-country\-/i", $trackingCodeStr)){
		$trackingCodeStr = preg_replace("/\-country\-/i", "-^all^-", $trackingCodeStr);
		return $trackingCodeStr;
	}
	
	$trackingCodeSearchArr = array(
	'CTY-AMARILLO' => 'AMARILLO',
	'CTY-AMES' => 'AMES',
	'CTY-ARLINGTONTX' => 'ARLINGTONTX',
	'CTY-ARVADA' => 'ARVADA',
	'CTY-AUBURN' => 'AUBURN',
	'CTY-AUSTIN' => 'AUSTIN',
	'CTY-BATONROUGE' => 'BATONROUGE',
	'CTY-BEAUMONT' => 'BEAUMONT',
	'CTY-BIRMINGHAM' => 'BIRMINGHAM',
	'CTY-BOWLINGGREEN' => 'BOWLINGGREEN',
	'CTY-CEDARRAPIDS' => 'CEDARRAPIDS',
	'CTY-CHATTANOOGA' => 'CHATTANOOGA',
	'CTY-CHICAGO' => 'CHICAGO',
	'CTY-CLEVELAND' => 'CLEVELAND',
	'CTY-CORPUSCHRISTI' => 'CORPUSCHRISTI',
	'CTY-DALLAS' => 'DALLAS',
	'CTY-DECATUR' => 'DECATUR',
	'CTY-DEKALB' => 'DEKALB',
	'CTY-DESMOINES' => 'DESMOINES',
	'CTY-FONDDULAC' => 'FONDDULAC',
	'CTY-GARLAND' => 'GARLAND',
	'CTY-GRANDEPRARIE' => 'GRANDEPRARIE',
	'CTY-HATTIESBURG' => 'HATTIESBURG',
	'CTY-HOUSTON' => 'HOUSTON',
	'CTY-INDEPENDENCE' => 'INDEPENDENCE',
	'CTY-IRVING' => 'IRVING',
	'CTY-JACKSON' => 'JACKSON',
	'CTY-JEFFERSONCITY' => 'JEFFERSONCITY',
	'CTY-KANSASCITYMO' => 'KANSASCITYMO',
	'CTY-KNOXVILLE' => 'KNOXVILLE',
	'CTY-LAFAYETTE' => 'LAFAYETTE',
	'CTY-LEESSUMMIT' => 'LEESSUMMIT',
	'CTY-LEXINGTON' => 'LEXINGTON',
	'CTY-LINCOLN' => 'LINCOLN',
	'CTY-LITTLEROCK' => 'LITTLEROCK',
	'CTY-LOUISVILLE' => 'LOUISVILLE',
	'CTY-LUBBOCK' => 'LUBBOCK',
	'CTY-MANDVILLE' => 'MANDVILLE',
	'CTY-MEMPHIS' => 'MEMPHIS',
	'CTY-MILWAUKEE' => 'MILWAUKEE',
	'CTY-MINNEAPOLIS' => 'MINNEAPOLIS',
	'CTY-MOBILE' => 'MOBILE',
	'CTY-MONTGOMERY' => 'MONTGOMERY',
	'CTY-NAPERVILLE' => 'NAPERVILLE',
	'CTY-NASHVILLE' => 'NASHVILLE',
	'CTY-NEWORLEANS' => 'NEWORLEANS',
	'CTY-OKLAHOMACITY' => 'OKLAHOMACITY',
	'CTY-OLATHE' => 'OLATHE',
	'CTY-OMAHA' => 'OMAHA',
	'CTY-OVERLANDPARK' => 'OVERLANDPARK',
	'CTY-PEORIA' => 'PEORIA',
	'CTY-PLANO' => 'PLANO',
	'CTY-ROCKFORD' => 'ROCKFORD',
	'CTY-SANANTONIO' => 'SANANTONIO',
	'CTY-SHERMAN' => 'SHERMAN',
	'CTY-SHREVEPORT' => 'SHREVEPORT',
	'CTY-SIOUXFALLS' => 'SIOUXFALLS',
	'CTY-SPRINGFIELDIL' => 'SPRINGFIELDIL',
	'CTY-SPRINGFIELDMO' => 'SPRINGFIELDMO',
	'CTY-ST.PAUL' => 'STPAUL',
	'CTY-TOPEKA' => 'TOPEKA',
	'CTY-TULSA' => 'TULSA',
	'CTY-VICTORIA' => 'VICTORIA',
	'CTY-WESTMINSTER' => 'WESTMINSTER',
	'STATE-ALABAMA' => 'ALABAMA',
	'STATE-ARKANSAS' => 'ARKANSAS',
	'STATE-ILLINOIS' => 'ILLINOIS',
	'STATE-IOWA' => 'IOWA',
	'STATE-UTAH' => 'UTAH',
	'STATE-KANSAS' => 'KANSAS',
	'STATE-KANS' => 'KANSAS',
	'STATE-KENTUCKY' => 'KENTUCKY',
	'STATE-LOUISIANA' => 'LOUISIANA',
	'STATE-MINNESOTA' => 'MINNESOTA',
	'STATE-MISSISSIPPI' => 'MISSISSIPPI',
	'STATE-MISSOURI' => 'MISSOURI',
	'STATE-NEBRASKA' => 'NEBRASKA',
	'STATE-NORTHDAKOTA' => 'NORTHDAKOTA',
	'STATE-OKLAHOMA' => 'OKLAHOMA',
	'STATE-SOUTHDAKOTA' => 'SOUTHDAKOTA',
	'STATE-TENNESSEE' => 'TENNESSEE',
	'STATE-TEXAS' => 'TEXAS',
	'STATE-WISCONSIN' => 'WISCONSIN',
	'CTY-AKRON' => 'AKRON',
	'CTY-ALEXANDRIA' => 'ALEXANDRIA',
	'CTY-ALLENTOWN' => 'ALLENTOWN',
	'CTY-ANNARBOR' => 'ANNARBOR',
	'CTY-ARLINGTONVA' => 'ARLINGTONVA',
	'CTY-CORALSPRINGS' => 'CORALSPRINGS',
	'CTY-ATLANTA' => 'ATLANTA',
	'CTY-AUGUSTA' => 'AUGUSTA',
	'CTY-BALTIMORE' => 'BALTIMORE',
	'CTY-BANGOR' => 'BANGOR',
	'CTY-BOSTON' => 'BOSTON',
	'CTY-BRIDGEPORT' => 'BRIDGEPORT',
	'CTY-BROOKLYN' => 'BROOKLYN',
	'CTY-BUFFALO' => 'BUFFALO',
	'CTY-CAPECORAL' => 'CAPECORAL',
	'CTY-CARY' => 'CARY',
	'CTY-CHARLESTON' => 'CHARLESTON',
	'CTY-CHARLOTTE' => 'CHARLOTTE',
	'CTY-CINCINNATI' => 'CINCINNATI',
	'CTY-CLEVELAND' => 'CLEVELAND',
	'CTY-COLUMBIA' => 'COLUMBIA',
	'CTY-COLUMBUS' => 'COLUMBUS',
	'CTY-COLUMBUSGA' => 'COLUMBUSGA',
	'CTY-DAYTON' => 'DAYTON',
	'CTY-DC' => 'WASHINGTONDC',
	'CTY-DETROIT' => 'DETROIT',
	'CTY-ELIZABETH' => 'ELIZABETH',
	'CTY-ERIE' => 'ERIE',
	'CTY-EVANSVILLE' => 'EVANSVILLE',
	'CTY-FAYETTEVILLE' => 'FAYETTEVILLE',
	'CTY-FLINT' => 'FLINT',
	'CTY-FORTWAYNE' => 'FORTWAYNE',
	'CTY-FTLAUDERDALE' => 'FTLAUDERDALE',
	'CTY-GAINSVILLE' => 'GAINSVILLE',
	'CTY-GOLDSBORO' => 'GOLDSBORO',
	'CTY-GRANDRAPIDS' => 'GRANDRAPIDS',
	'CTY-GREENBAY' => 'GREENBAY',
	'CTY-GREENSBORO' => 'GREENSBORO',
	'CTY-HARTFORD' => 'HARTFORD',
	'CTY-HOLLYWOOD' => 'HOLLYWOOD',
	'CTY-INDIANAPOLIS' => 'INDIANAPOLIS',
	'CTY-ITHACA' => 'ITHACA',
	'CTY-JACKSONVILLE' => 'JACKSONVILLE',
	'CTY-LANSING' => 'LANSING',
	'CTY-LOWELL' => 'LOWELL',
	'CTY-MANCHESTER' => 'MANCHESTER',
	'CTY-MIAMI' => 'MIAMI',
	'CTY-MIRAMAR' => 'MIRAMAR',
	'CTY-MORGANTOWN' => 'MORGANTOWN',
	'CTY-MIDDLETOWN' => 'MIDDLETOWN',
	'CTY-NEWARK' => 'NEWARK',
	'CTY-NEWPORTNEWS' => 'NEWPORTNEWS',
	'CTY-NORFOLK' => 'NORFOLK',
	'CTY-NYC' => 'NEWYORK',
	'CTY-NY' => 'NEWYORK',
	'CTY-ORLANDO' => 'ORLANDO',
	'CTY-ORLAN' => 'ORLANDO',
	'CTY-PEMBROKEPINES' => 'PEMBROKEPINES',
	'CTY-PHILADELPHIA' => 'PHILADELPHIA',
	'CTY-POMPANOBEACH' => 'POMPANOBEACH',
	'CTY-PORTSMOUTH' => 'PORTSMOUTH',
	'CTY-PORTSTLUCIE' => 'PORTSTLUCIE',
	'CTY-PROVIDENCE' => 'PROVIDENCE',
	'CTY-RALEIGH' => 'RALEIGH',
	'CTY-RICHMOND' => 'RICHMOND',
	'CTY-ROCHESTER' => 'ROCHESTER',
	'CTY-SALISBURY' => 'SALISBURY',
	'CTY-SARATOGASPRINGS' => 'SARATOGASPRINGS',
	'CTY-SAVANNAH' => 'SAVANNAH',
	'CTY-SPRINGFIELD' => 'SPRINGFIELDMA',
	'CTY-STAMFORD' => 'STAMFORD',
	'CTY-STERLINGHEIGHTS' => 'STERLINGHEIGHTS',
	'CTY-SUMTER' => 'SUMTER',
	'CTY-SYRACUSE' => 'SYRACUSE',
	'CTY-TALLAHASSEE' => 'TALLAHASSEE',
	'CTY-TAMPA' => 'TAMPA',
	'CTY-TOLEDO' => 'TOLEDO',
	'CTY-VIRGINIABEACH' => 'VIRGINIABEACH',
	'CTY-WARREN' => 'WARREN',
	'CTY-WINCHESTER' => 'WINCHESTER',
	'CTY-WINSTONSALEM' => 'WINSTONSALEM',
	'CTY-WORCESTER' => 'WORCESTER',
	'CTY-YONKERS' => 'YONKERS',
	'STATE-CONNECTICUT' => 'CONNECTICUT',
	'STATE-DELEWARE' => 'DELEWARE',
	'STATE-FLORIDA' => 'FLORIDA',
	'STATE-GEORGIA' => 'GEORGIA',
	'STATE-INDIANA' => 'INDIANA',
	'STATE-MAINE' => 'MAINE',
	'STATE-MARYLAND' => 'MARYLAND',
	'STATE-MASSACHUSETTS' => 'MASSACHUSETTS',
	'STATE-MICHIGAN' => 'MICHIGAN',
	'STATE-NEWHAMPSHIRE' => 'NEWHAMPSHIRE',
	'STATE-NEWJERSEY' => 'NEWJERSEY',
	'STATE-NEWYORK' => 'NEWYORK',
	'STATE-NORTHCAROLINA' => 'NORTHCAROLINA',
	'STATE-OHIO' => 'OHIO',
	'STATE-HAWAII' => 'HAWAII',
	'STATE-PENNSYLVANIA' => 'PENNSYLVANIA',
	'STATE-RHODEISLAND' => 'RHODEISLAND',
	'STATE-SOUTHCAROLINA' => 'SOUTHCAROLINA',
	'STATE-VERMONT' => 'VERMONT',
	'STATE-VIRGINIA' => 'VIRGINIA',
	'STATE-WESTVIRGINIA' => 'WESTVIRGINIA',
	'CTY-ALBUQUERQUE' => 'ALBUQUERQUE',
	'CTY-AURORA' => 'AURORA',
	'CTY-BOISE' => 'BOISE',
	'CTY-CASPER' => 'CASPER',
	'CTY-COLORADOSPRINGS' => 'COLORADOSPRINGS',
	'CTY-DENVER' => 'DENVER',
	'CTY-FLAGSTAFF' => 'FLAGSTAFF',
	'CTY-PUEBLO' => 'PUEBLO',
	'CTY-CONNELLSVILLE' => 'CONNELLSVILLE',
	'CTY-GILBERTTOWN' => 'GILBERTTOWN',
	'CTY-GLENDALE' => 'GLENDALE',
	'CTY-GREATFALLS' => 'GREATFALLS',
	'CTY-JOLIET' => 'JOLIET',
	'CTY-LAFAYETTE' => 'LAFAYETTE',
	'CTY-MESA' => 'MESA',
	'CTY-PHOENIX' => 'PHOENIX',
	'CTY-PRESCOTT' => 'PRESCOTT',
	'CTY-SALTLAKECITY' => 'SALTLAKECITY',
	'CTY-SCOTTSDALE' => 'SCOTTSDALE',
	'CTY-ST.GEORGE' => 'STGEORGE',
	'CTY-TEMPE' => 'TEMPE',
	'CTY-TUCSON' => 'TUCSON',
	'STATE-ARIZONA' => 'ARIZONA',
	'STATE-COLORADO' => 'COLORADO',
	'STATE-IDAHO' => 'IDAHO',
	'STATE-MONTANA' => 'MONTANA',
	'STATE-NEWMEXICO' => 'NEWMEXICO',
	'STATE-WYOMING' => 'WYOMING',
	'OTHER_CTY-ANCHORAGE' => 'ANCHORAGE',
	'OTHER_CTY-HONOLULU' => 'HONOLULU',
	'OTHER_STATE-ALASKA' => 'ALASKA',
	'OTHER_STATE-HAWAII' => 'HAWAII',
	'CTY-ANAHEIM' => 'ANAHEIM',
	'CTY-BAKERSFIELD' => 'BAKERSFIELD',
	'CTY-BELLEVUE' => 'BELLEVUE',
	'CTY-BEND' => 'BEND',
	'CTY-BERKELEY' => 'BERKELEY',
	'CTY-CAMARILLO' => 'CAMARILLO',
	'CTY-CORONA' => 'CORONA',
	'CTY-CORVALLIS' => 'CORVALLIS',
	'CTY-KINGSTON' => 'KINGSTON',
	'CTY-ELPASO' => 'ELPASO',
	'CTY-JONESBORO' => 'JONESBORO',
	'CTY-PASADENATX' => 'PASADENATX',
	'CTY-MADERA' => 'MADERA',
	'CTY-CUMBERLAND' => 'CUMBERLAND',
	'CTY-DALTON' => 'DALTON',
	'CTY-HARRISONBURG' => 'HARRISONBURG',
	'CTY-HAZLETON' => 'HAZLETON',
	'CTY-KOKOMO' => 'KOKOMO',
	'CTY-LEBANON' => 'LEBANON',
	'CTY-MONESSEN' => 'MONESSEN',
	'CTY-MONROE' => 'MONROE',
	'CTY-ROME' => 'ROME',
	'CTY-SANDUSKY' => 'SANDUSKY',
	'CTY-VALDOSTA' => 'VALDOSTA',
	'CTY-CARSONCITY' => 'CARSONCITY',
	'CTY-GRANDFORKS' => 'GRANDFORKS',
	'CTY-SALEM' => 'SALEM',
	'CTY-BRISTOL' => 'BRISTOL',
	'CTY-BROWNSVILLE' => 'BROWNSVILLE',
	'CTY-CLARKSVILLE' => 'CLARKSVILLE',
	'CTY-GADSDEN' => 'GADSDEN',
	'CTY-LEWISTON' => 'LEWISTON',
	'CTY-BRUNSWICK' => 'BRUNSWICK',
	'CTY-PASCAGOULA' => 'PASCAGOULA',
	'CTY-PINEBLUFF' => 'PINEBLUFF',
	'CTY-RADCLIFF' => 'RADCLIFF',
	'CTY-CAPEMAY' => 'CAPEMAY',
	'CTY-GALVESTON' => 'GALVESTON',
	'CTY-ELCENTRO' => 'ELCENTRO',
	'CTY-INGLEWOOD' => 'INGLEWOOD',
	'CTY-MANTECA' => 'MANTECA',
	'CTY-LONGVIEW' => 'LONGVIEW',
	'CTY-MORRISTOWN' => 'MORRISTOWN',
	'CTY-LOMPOC' => 'LOMPOC',
	'CTY-DOTHAN' => 'DOTHAN',
	'CTY-DANVILLE' => 'DANVILLE',
	'CTY-ABILENE' => 'ABILENE',
	'CTY-CONCORD' => 'CONCORD',
	'CTY-BURBANK' => 'BURBANK',
	'CTY-ANTIOCH' => 'ANTIOCH',
	'CTY-ZEPHYRHILLS' => 'ZEPHYRHILLS',
	'CTY-WATERBURY' => 'WATERBURY',
	'CTY-STAUGUSTINE' => 'STAUGUSTINE',
	'CTY-SOUTHBEND' => 'SOUTHBEND',
	'CTY-ROCKYMOUNT' => 'ROCKYMOUNT',
	'CTY-PATERSON' => 'PATERSON',
	'CTY-NEWHAVEN' => 'NEWHAVEN',
	'CTY-LADYLAKE' => 'LADYLAKE',
	'CTY-JERSEYCITY' => 'JERSEYCITY',
	'CTY-HINESVILLE' => 'HINESVILLE',
	'CTY-HAMPTON' => 'HAMPTON',
	'CTY-CHESAPEAKE' => 'CHESAPEAKE',
	'CTY-BLACKSBURG' => 'BLACKSBURG',
	'CTY-TORRANCE' => 'TORRANCE',
	'CTY-COSTAMESA' => 'COSTAMESA',
	'CTY-DALYCITY' => 'DALYCITY',
	'CTY-DOWNEY' => 'DOWNEY',
	'CTY-ELKGROVE' => 'ELKGROVE',
	'CTY-ELMONTE' => 'ELMONTE',
	'CTY-MADISON' => 'MADISON',
	'CTY-HUNTSVILLE' => 'HUNTSVILLE',
	'CTY-HONOLULU' => 'HONOLULU',
	'CTY-FORTCOLLINS' => 'FORTCOLLINS',
	'CTY-ANCHORAGE' => 'ANCHORAGE',
	'CTY-FAIRBANKS' => 'FAIRBANKS',
	'CTY-ESCONDIDO' => 'ESCONDIDO',
	'CTY-EUGENE' => 'EUGENE',
	'CTY-FAIRFIELD' => 'FAIRFIELD',
	'CTY-FONTANA' => 'FONTANA',
	'CTY-FREMONT' => 'FREMONT',
	'CTY-FRESNO' => 'FRESNO',
	'CTY-FULLERTON' => 'FULLERTON',
	'CTY-GARDENGROVE' => 'GARDENGROVE',
	'CTY-GLENDALE' => 'GLENDALE',
	'CTY-HAYWARD' => 'HAYWARD',
	'CTY-HUNTINGTONBEACH' => 'HUNTINGTONBEACH',
	'CTY-IRVINE' => 'IRVINE',
	'CTY-LANCASTER' => 'LANCASTER',
	'CTY-LASVEGAS' => 'LASVEGAS',
	'CTY-LOSANGELES' => 'LOSANGELES',
	'Cty-LosAn' => 'LOSANGELES',
	'CTY-MODESTO' => 'MODESTO',
	'CTY-MORENOVALLEY' => 'MORENOVALLEY',
	'CTY-OAKLAND' => 'OAKLAND',
	'CTY-ONTARIO' => 'ONTARIO',
	'CTY-PORTERVILLE' => 'PORTERVILLE',
	'CTY-WACO' => 'WACO',
	'CTY-ORANGE' => 'ORANGE',
	'CTY-OXNARD' => 'OXNARD',
	'CTY-PASADENACA' => 'PASADENACA',
	'CTY-PETALUMA' => 'PETALUMA',
	'CTY-POMONA' => 'POMONA',
	'CTY-PORTLAND' => 'PORTLAND',
	'CTY-RANCHOCUCAMONGA' => 'RANCHOCUCAMONGA',
	'CTY-RIVERSIDE' => 'RIVERSIDE',
	'CTY-SACRAMENTO' => 'SACRAMENTO',
	'CTY-SANBERNARDINO' => 'SANBERNARDINO',
	'CTY-SANDIEGO' => 'SANDIEGO',
	'CTY-SANFRANCISCO' => 'SANFRANCISCO',
	'CTY-SanF' => 'SANFRANCISCO',
	'CTY-SANLUISOBISPO' => 'SANLUISOBISPO',
	'CTY-SANTACLARACA' => 'SANTACLARACA',
	'CTY-SANTAROSA' => 'SANTAROSA',
	'CTY-SEATTLE' => 'SEATTLE',
	'CTY-SIMIVALLEY' => 'SIMIVALLEY',
	'CTY-SPOKANE' => 'SPOKANE',
	'CTY-KANSASCITYKS' => 'KANSASCITYKS',
	'CTY-SALINAS' => 'SALINAS',
	'CTY-DALTON' => 'DALTON',
	'CTY-STOCKTON' => 'STOCKTON',
	'CTY-SUNNYVALE' => 'SUNNYVALE',
	'CTY-THOUSANDOAKS' => 'THOUSANDOAKS',
	'CTY-TRACY' => 'TRACY',
	'CTY-VALLEJO' => 'VALLEJO',
	'CTY-VANCOUVER' => 'VANCOUVER',
	'CTY-WENATCHEE' => 'WENATCHEE',
	'CTY-WESTCOVINA' => 'WESTCOVINA',
	'CTY-SANTACLARITA' => 'SANTACLARITA',
	'CTY-PALMDALE' => 'PALMDALE',
	'CTY-OCEANSIDE' => 'OCEANSIDE',
	'CTY-NORWALK' => 'NORWALK',
	'CTY-VISALIA' => 'VISALIA',
	'CTY-NLASVEGAS' => 'LASVEGAS',
	'CTY-INGLEWOOD' => 'INGLEWOOD',
	'CTY-ROSEVILLE' => 'ROSEVILLE',
	'CTY-SALINAS' => 'SALINAS',
	'CTY-TORRANCE' => 'TORRANCE',
	'CTY-VENTURA' => 'VENTURA',
	'STATE-CALIFORNIA' => 'CALIFORNIA',
	'Cty-California' => 'CALIFORNIA',
	'STATE-NEVADA' => 'NEVADA',
	'Cty-Nevada' => 'NEVADA',
	'STATE-OREGON' => 'OREGON',
	'STATE-WASHINGTON' => 'WASHINGTON',
	'Cty-Washington' => 'WASHINGTON',
	'STATE-ALASKA' => 'ALASKA',
	'STATE-CONNECTICUT' => 'CONNECTICUT',
	'STATE-FLORIDA' => 'FLORIDA',
	'STATE-GEORGIA' => 'GEORGIA',
	'STATE-MARYLAND' => 'MARYLAND',
	'STATE-MASSACHUSETTS' => 'MASSACHUSETTS',
	'STATE-NEWJERSEY' => 'NEWJERSEY',
	'STATE-NORTHCAROLINA' => 'NORTHCAROLINA',
	'STATE-PENNSYLVANIA' => 'PENNSYLVANIA',
	'STATE-SOUTHDAKOTA' => 'SOUTHDAKOTA',
	'STATE-VIRGINIA' => 'VIRGINIA',
	'MILWAUKEECTY-MILWAUKEE' => 'MILWAUKEE',
	'PERSONALSTATE-LOUISIANA' => 'LOUISIANA',
	'MIAMICTY-MIAMI' => 'MIAMI',
	'MODESTOCTY-COSTAMESA' => 'COSTAMESA',
	'VETCTY-COLUMBUS' => 'COLUMBUS',
	'PERSONALCTY-NYC' => 'NEWYORK',
	'PERSONALSTATE-FLORIDA' => 'FLORIDA',
	'PHOENIXCTY-PHOENIX' => 'PHOENIX',
	'SANDIEGOCTY-SANDIEGO' => 'SANDIEGO',
	'MUSICBCCTY-AUSTIN' => 'AUSTIN',
	'NAVYCTY-ATLANTA' => 'ATLANTA',
	'NAVYSTATE-FLORIDA' => 'FLORIDA',
	'NEWYORKCTY-NYC' => 'NEWYORK',
	'ACIFIC_CTY-SEATTLE' => 'SEATTLE',
	'TITUSVILLE' => 'TITUSVILLE',
	'BAKERSTATE-TEXAS' => 'TEXAS',
	'BAKERSTATE-NEWYORK' => 'NEWYORK',
	'BCTY-CHICAGO' => 'CHICAGO',
	'BSTATE-ILLINOIS' => 'ILLINOIS',
	'BEAUTYCTY-BUFFALO' => 'BUFFALO',
	'CARDSSTATE-MISSOURI' => 'MISSOURI',
	'CHARLOTTECTY-CHARLOTTE' => 'CHARLOTTE',
	'CHICAGOCTY-CHICAGO' => 'CHICAGO',
	'COLORADOSTATE-COLORADO' => 'COLORADO',
	'DALLASCTY-DALLAS' => 'DALLAS',
	'CTY-ATLANTA' => 'ATLANTA',
	'CTY-OKLAHOMACITY' => 'OKLAHOMACITY',
	'CTY-KANSASCITY' => 'KANSASCITY',
	'CTY-FARMINGTON' => 'FARMINGTON',
	'NORMAN' => 'NORMAN',
	'GLENSFALLS' => 'GLENSFALLS',
	'COLUMBUS' => 'COLUMBUS',
	'CTY-RICHMOND' => 'RICHMOND'
	);
	
	$replaceZoneNumber = array(
	'LOSANGELES' => '2',
	'SANFRANCISCO' => '2',
	'LASVEGAS' => '3',
	'SANDIEGO' => '2',
	'SACRAMENTO' => '4',
	'PORTLAND' => '5',
	'FRESNO' => '2',
	'SEATTLE' => '5',
	'OAKLAND' => '4',
	'HONOLULU' => '44',
	'ANAHEIM' => '2',
	'RIVERSIDE' => '2',
	'BAKERSFIELD' => '2',
	'STOCKTON' => '3',
	'FREMONT' => '4',
	'SPOKANE' => '5',
	'GLENDALE' => '2',
	'HUNTINGTONBEACH' => '2',
	'CALIFORNIA' => '2',
	'NEVADA' => '4',
	'OREGON' => '5',
	'WASHINGTON' => '5',
	'HAWAII' => '44',
	'ALASKA' => '44',
	'FONTANA' => '2',
	'KANSASCITY' => '6',
	'GARDENGROVE' => '2',
	'IRVINE' => '2',
	'WINSTONSALEM' => '8',
	'CORALSPRINGS' => '8',
	'DALTON' => '8',
	'TOLEDO' => '8',
	'MODESTO' => '3',
	'MORENOVALLEY' => '2',
	'OCEANSIDE' => '2',
	'ONTARIO' => '2',
	'OXNARD' => '2',
	'PASADENACA' => '2',
	'RANCHOCUCAMONGA' => '2',
	'SANBERNARDINO' => '2',
	'SANTACLARITA' => '2',
	'VENTURA' => '2',
	'SIMIVALLEY' => '2',
	'ANCHORAGE' => '44',
	'VANCOUVER' => '5',
	'POMONA' => '2',
	'SANTAROSA' => '4',
	'CORONA' => '2',
	'SALINAS' => '3',
	'SALEM' => '5',
	'EUGENE' => '5',
	'TORRANCE' => '2',
	'HAYWARD' => '4',
	'ORANGE' => '2',
	'PALMDALE' => '2',
	'ESCONDIDO' => '2',
	'LANCASTER' => '2',
	'FULLERTON' => '2',
	'SUNNYVALE' => '4',
	'THOUSANDOAKS' => '2',
	'CONCORD' => '4',
	'ELMONTE' => '2',
	'VALLEJO' => '4',
	'INGLEWOOD' => '2',
	'BELLEVUE' => '5',
	'ELKGROVE' => '4',
	'COSTAMESA' => '2',
	'DOWNEY' => '2',
	'VISALIA' => '2',
	'WESTCOVINA' => '2',
	'ROSEVILLE' => '4',
	'NORWALK' => '2',
	'SANTACLARACA' => '3',
	'FAIRFIELD' => '4',
	'BURBANK' => '2',
	'BERKELEY' => '4',
	'ANTIOCH' => '4',
	'DALYCITY' => '4',
	'FAIRBANKS' => '7',
	'DECATUR' => '7',
	'JONESBORO' => '7',
	'PINEBLUFF' => '7',
	'FLAGSTAFF' => '4',
	'MANTECA' => '3',
	'ELCENTRO' => '2',
	'SANLUISOBISPO' => '2',
	'LOMPOC' => '2',
	'MADERA' => '3',
	'TRACY' => '3',
	'PETALUMA' => '4',
	'LADYLAKE' => '8',
	'TITUSVILLE' => '8',
	'STAUGUSTINE' => '8',
	'ZEPHYRHILLS' => '8',
	'HINESVILLE' => '8',
	'BRUNSWICK' => '8',
	'VALDOSTA' => '8',
	'DALTON' => '8',
	'ROME' => '8',
	'AMES' => '7',
	'LEWISTON' => '8',
	'DANVILLE' => '7',
	'DEKALB' => '7',
	'BANGOR' => '8',
	'LEESSUMMIT' => '6',
	'SALISBURY' => '8',
	'CARSONCITY' => '4',
	'BOWLINGGREEN' => '7',
	'COLUMBUS' => '8',
	'CUMBERLAND' => '8',
	'MONROE' => '8',
	'PASCAGOULA' => '7',
	'GOLDSBORO' => '8',
	'GRANDFORKS' => '7',
	'PORTSMOUTH' => '8',
	'CAPEMAY' => '8',
	'MIDDLETOWN' => '8',
	'JEFFERSONCITY' => '7',
	'SARATOGASPRINGS' => '8',
	'ITHACA' => '8',
	'GLENSFALLS' => '8',
	'SANDUSKY' => '8',
	'BEND' => '5',
	'CORVALLIS' => '5',
	'HAZLETON' => '8',
	'MONESSEN' => '8',
	'CONNELLSVILLE' => '8',
	'MORRISTOWN' => '8',
	'CLEVELAND' => '8',
	'BRISTOL' => '8',
	'GALVESTON' => '7',
	'SHERMAN' => '6',
	'WACO' => '6',
	'ELPASO' => '6',
	'ARLINGTONTX' => '6',
	'DANVILLE' => '8',
	'HARRISONBURG' => '8',
	'WINCHESTER' => '8',
	'BLACKSBURG' => '8',
	'MOUNTVERNON' => '5',
	'WENATCHEE' => '5',
	'FONDDULAC' => '7',
	'CASPER' => '5',
	'AUBURN' => '8',
	'PORTERVILLE' => '2',
	'LAFAYETTE' => '5',
	'LONGVIEW' => '5',
	'DOTHAN' => '8',
	'HATTIESBURG' => '7',
	'VICTORIA' => '6',
	'ROCKYMOUNT' => '8',
	'GADSDEN' => '8',
	'PRESCOTT' => '4',
	'POCATELLO' => '5',
	'STGEORGE' => '4',
	'CAMARILLO' => '2',
	'MANDEVILLE' => '7',
	'LEBANON' => '8',
	'KOKOMO' => '7',
	'PASADENATX' => '6',
	'SUMTER' => '8',
	'GREATFALLS' => '6',
	'RADCLIFF' => '8',
	'CHATTANOOGA' => '8',
	'BROWNSVILLE' => '6',
	'OVERLANDPARK' => '6',
	'TEMPE' => '4',
	'ROCKFORD' => '7',
	'BOISE' => '5',
	'HUNTSVILLE' => '7',
	'LITTLEROCK' => '7',
	'AMARILLO' => '5',
	'KNOXVILLE' => '8',
	'SALTLAKECITY' => '4',
	'JACKSON' => '7',
	'GILBERTTOWN' => '4',
	'KANSASCITY' => '6',
	'IOWA' => '7',
	'ILLINOIS' => '7',
	'KANSAS' => '6',
	'MINNESOTA' => '7',
	'MISSOURI' => '6',
	'NEBRASKA' => '6',
	'OKLAHOMA' => '6',
	'WISCONSIN' => '7',
	'ALABAMA' => '7',
	'ARKANSAS' => '7',
	'KENTUCKY' => '8',
	'LOUISIANA' => '7',
	'MISSISSIPPI' => '7',
	'TENNESSEE' => '7',
	'TEXAS' => '6',
	'NORTHDAKOTA' => '7',
	'SOUTHDAKOTA' => '6',
	'IDAHO' => '5',
	'ARIZONA' => '4',
	'NEWMEXICO' => '5',
	'COLORADO' => '5',
	'PUEBLO' => '5',
	'KINGSTON' => '8',
	'UTAH' => '4',
	'MONTANA' => '6',
	'WYOMING' => '5',
	'BIRMINGHAM' => '7',
	'MOBILE' => '8',
	'MONTGOMERY' => '7',
	'DESMOINES' => '7',
	'CHICAGO' => '7',
	'LEXINGTON' => '8',
	'LOUISVILLE' => '8',
	'BATONROUGE' => '7',
	'NEWORLEANS' => '7',
	'SHREVEPORT' => '6',
	'MINNEAPOLIS' => '7',
	'STPAUL' => '7',
	'KANSASCITYMO' => '6',
	'SPRINGFIELDMO' => '6',
	'LINCOLN' => '6',
	'OMAHA' => '6',
	'OKLAHOMACITY' => '6',
	'TULSA' => '6',
	'MEMPHIS' => '7',
	'NASHVILLE' => '7',
	'ARLINGTONVA' => '6',
	'AUSTIN' => '6',
	'CORPUSCHRISTI' => '6',
	'DALLAS' => '6',
	'GARLAND' => '6',
	'HOUSTON' => '6',
	'IRVING' => '6',
	'LUBBOCK' => '5',
	'PLANO' => '6',
	'SANANTONIO' => '6',
	'MADISON' => '7',
	'MILWAUKEE' => '7',
	'GLENDALE' => '4',
	'MESA' => '4',
	'PHOENIX' => '4',
	'SCOTTSDALE' => '4',
	'TUCSON' => '4',
	'AURORA' => '5',
	'COLORADOSPRINGS' => '5',
	'DENVER' => '5',
	'ALBUQUERQUE' => '5',
	'SPRINGFIELDIL' => '7',
	'JOLIET' => '7',
	'GRANDEPRARIE' => '6',
	'PASADENA' => '6',
	'NAPERVILLE' => '7',
	'SIOUXFALLS' => '6',
	'PEORIA' => '4',
	'FORTCOLLINS' => '5',
	'CEDARRAPIDS' => '7',
	'TOPEKA' => '6',
	'ABILENE' => '6',
	'KANSASCITYKS' => '6',
	'CLARKSVILLE' => '7',
	'LAFAYETTE' => '7',
	'BEAUMONT' => '7',
	'OLATHE' => '6',
	'INDEPENDENCE' => '5',
	'WESTMINSTER' => '5',
	'ARVADA' => '5',
	'PEUBLO' => '5',
	'NORMAN' => '5',
	'FLORIDA' => '8',
	'GEORGIA' => '8',
	'INDIANA' => '7',
	'MICHIGAN' => '8',
	'OHIO' => '8',
	'MASSACHUSETTS' => '8',
	'MARYLAND' => '8',
	'NEWJERSEY' => '8',
	'NEWYORK' => '8',
	'PENNSYLVANIA' => '8',
	'RHODEISLAND' => '8',
	'NORTHCAROLINA' => '8',
	'VIRGINIA' => '8',
	'VIRGINIABEACH' => '8',
	'SOUTHCAROLINA' => '8',
	'MAINE' => '8',
	'NEWHAMPSHIRE' => '8',
	'VERMONT' => '8',
	'CONNECTICUT' => '8',
	'DELEWARE' => '8',
	'WESTVIRGINIA' => '8',
	'MORGANTOWN' => '8',
	'JACKSONVILLE' => '8',
	'MIAMI' => '8',
	'MIRAMAR' => '8',
	'ORLANDO' => '8',
	'TAMPA' => '8',
	'ATLANTA' => '8',
	'AUGUSTA' => '8',
	'FORTWAYNE' => '8',
	'INDIANAPOLIS' => '7',
	'BOSTON' => '8',
	'BALTIMORE' => '8',
	'DETROIT' => '8',
	'GRANDRAPIDS' => '7',
	'CHARLOTTE' => '8',
	'GREENSBORO' => '8',
	'RALEIGH' => '8',
	'JERSEYCITY' => '8',
	'NEWARK' => '8',
	'BUFFALO' => '8',
	'NEWYORK' => '8',
	'ROCHESTER' => '8',
	'YONKERS' => '8',
	'AKRON' => '8',
	'CINCINNATI' => '8',
	'CLEVELAND' => '8',
	'COLUMBUS' => '8',
	'TOLDEO' => '8',
	'PHILADELPHIA' => '8',
	'ARLINGTONVA' => '8',
	'CHESAPEAKE' => '8',
	'NORFOLK' => '8',
	'RICHMOND' => '8',
	'VIRGINABEACH' => '8',
	'WASHINGTONDC' => '8',
	'TALLAHASSEE' => '8',
	'COLUMBUS' => '8',
	'WORCESTER' => '8',
	'SALEM' => '8',
	'DAYTON' => '8',
	'PROVIDENCE' => '8',
	'NEWPORTNEWS' => '8',
	'PEMBROKEPINES' => '8',
	'SPRINGFIELDMA' => '8',
	'BROOKLYN' => '8',
	'PATERSON' => '8',
	'HAMPTON' => '8',
	'SYRACUSE' => '8',
	'FTLAUDERDALE' => '8',
	'HOLLYWOOD' => '8',
	'CAPECORAL' => '8',
	'BRIDGEPORT' => '8',
	'ALEXANDRIA' => '8',
	'WARREN' => '8',
	'PORTSTLUCIE' => '8',
	'FAYETTEVILLE' => '8',
	'FARMINGTON' => '8',
	'POMPANOBEACH' => '8',
	'SAVANNAH' => '8',
	'STERLINGHEIGHTS' => '8',
	'ELIZABETH' => '8',
	'NEWHAVEN' => '8',
	'HARTFORD' => '8',
	'STAMFORD' => '8',
	'FLINT' => '8',
	'COLUMBIA' => '8',
	'EVANSVILLE' => '7',
	'LANSING' => '8',
	'ANNARBOR' => '8',
	'MANCHESTER' => '8',
	'GAINSVILLE' => '8',
	'WATERBURY' => '8',
	'ALLENTOWN' => '8',
	'CHARLESTON' => '8',
	'CARY' => '8',
	'SOUTHBEND' => '7',
	'MANDVILLE' => '7',
	'LOWELL' => '8',
	'ERIE' => '8',
	'GREENBAY' => '7',
	'PORTSMOUTH' => '8'
	);
	
	$replaceLocationType = array(
	'LOSANGELES' => 'B',
	'SANFRANCISCO' => 'B',
	'LASVEGAS' => 'B',
	'SANDIEGO' => 'B',
	'SACRAMENTO' => 'B',
	'PORTLAND' => 'B',
	'FRESNO' => 'B',
	'SEATTLE' => 'B',
	'OAKLAND' => 'B',
	'HONOLULU' => 'B',
	'ANAHEIM' => 'T',
	'RIVERSIDE' => 'T',
	'BAKERSFIELD' => 'T',
	'STOCKTON' => 'B',
	'WACO' => 'B',
	'ELPASO' => 'B',
	'KANSASCITY' => 'B',
	'FREMONT' => 'T',
	'SPOKANE' => 'B',
	'TOLEDO' => 'B',
	'GLENDALE' => 'T',
	'HUNTINGTONBEACH' => 'T',
	'CALIFORNIA' => 'S',
	'NEVADA' => 'S',
	'OREGON' => 'S',
	'WASHINGTON' => 'S',
	'HAWAII' => 'S',
	'ALASKA' => 'S',
	'FONTANA' => 'T',
	'GARDENGROVE' => 'T',
	'IRVINE' => 'T',
	'MODESTO' => 'T',
	'MORENOVALLEY' => 'T',
	'OCEANSIDE' => 'T',
	'ONTARIO' => 'T',
	'OXNARD' => 'T',
	'FARMINGTON' => 'T',
	'PASADENACA' => 'T',
	'RANCHOCUCAMONGA' => 'T',
	'SANBERNARDINO' => 'T',
	'SANTACLARITA' => 'T',
	'VENTURA' => 'T',
	'SIMIVALLEY' => 'T',
	'ANCHORAGE' => 'B',
	'ARLINGTONTX' => 'B',
	'VANCOUVER' => 'T',
	'POMONA' => 'T',
	'SANTAROSA' => 'T',
	'CORONA' => 'T',
	'SALINAS' => 'T',
	'SALEM' => 'B',
	'EUGENE' => 'T',
	'TORRANCE' => 'T',
	'HAYWARD' => 'T',
	'ORANGE' => 'T',
	'PALMDALE' => 'T',
	'ESCONDIDO' => 'T',
	'LANCASTER' => 'T',
	'FULLERTON' => 'T',
	'SUNNYVALE' => 'T',
	'THOUSANDOAKS' => 'T',
	'CONCORD' => 'T',
	'ELMONTE' => 'T',
	'KINGSTON' => 'T',
	'VALLEJO' => 'T',
	'INGLEWOOD' => 'T',
	'BELLEVUE' => 'T',
	'ELKGROVE' => 'T',
	'COSTAMESA' => 'T',
	'DOWNEY' => 'T',
	'VISALIA' => 'T',
	'WESTCOVINA' => 'T',
	'ROSEVILLE' => 'T',
	'MORGANTOWN' => 'T',
	'NORWALK' => 'T',
	'SANTACLARACA' => 'T',
	'FAIRFIELD' => 'T',
	'BURBANK' => 'T',
	'BERKELEY' => 'T',
	'MANDVILLE' => 'T',
	'CORALSPRINGS' => 'T',
	'ANTIOCH' => 'T',
	'DALYCITY' => 'T',
	'FAIRBANKS' => 'T',
	'DECATUR' => 'T',
	'JONESBORO' => 'T',
	'PINEBLUFF' => 'T',
	'FLAGSTAFF' => 'T',
	'MANTECA' => 'T',
	'PASADENATX' => 'T',
	'KANSASCITYKS' => 'B',
	'ELCENTRO' => 'T',
	'SANLUISOBISPO' => 'T',
	'LOMPOC' => 'T',
	'MADERA' => 'T',
	'TRACY' => 'T',
	'PETALUMA' => 'T',
	'LADYLAKE' => 'T',
	'TITUSVILLE' => 'T',
	'STAUGUSTINE' => 'T',
	'ZEPHYRHILLS' => 'T',
	'HINESVILLE' => 'T',
	'BRUNSWICK' => 'T',
	'VALDOSTA' => 'T',
	'DALTON' => 'T',
	'ROME' => 'T',
	'AMES' => 'T',
	'LEWISTON' => 'T',
	'DANVILLE' => 'T',
	'DEKALB' => 'T',
	'BANGOR' => 'B',
	'LEESSUMMIT' => 'T',
	'SALISBURY' => 'T',
	'CARSONCITY' => 'B',
	'BOWLINGGREEN' => 'T',
	'COLUMBUS' => 'T',
	'CUMBERLAND' => 'T',
	'MONROE' => 'B',
	'PASCAGOULA' => 'T',
	'GOLDSBORO' => 'T',
	'GRANDFORKS' => 'T',
	'PORTSMOUTH' => 'B',
	'CAPEMAY' => 'T',
	'MIDDLETOWN' => 'T',
	'JEFFERSONCITY' => 'T',
	'SARATOGASPRINGS' => 'T',
	'ITHACA' => 'B',
	'GLENSFALLS' => 'T',
	'SANDUSKY' => 'T',
	'BEND' => 'T',
	'CORVALLIS' => 'T',
	'HAZLETON' => 'T',
	'MONESSEN' => 'T',
	'CONNELLSVILLE' => 'T',
	'MORRISTOWN' => 'T',
	'CLEVELAND' => 'T',
	'BRISTOL' => 'T',
	'GALVESTON' => 'B',
	'SHERMAN' => 'T',
	'DANVILLE' => 'T',
	'HARRISONBURG' => 'T',
	'WINCHESTER' => 'T',
	'BLACKSBURG' => 'T',
	'MOUNTVERNON' => 'T',
	'WENATCHEE' => 'T',
	'FONDDULAC' => 'T',
	'CASPER' => 'B',
	'AUBURN' => 'T',
	'PORTERVILLE' => 'T',
	'LAFAYETTE' => 'T',
	'LONGVIEW' => 'T',
	'DOTHAN' => 'T',
	'HATTIESBURG' => 'T',
	'VICTORIA' => 'T',
	'ROCKYMOUNT' => 'T',
	'GADSDEN' => 'T',
	'PRESCOTT' => 'T',
	'POCATELLO' => 'B',
	'STGEORGE' => 'T',
	'CAMARILLO' => 'T',
	'MANDEVILLE' => 'T',
	'LEBANON' => 'T',
	'KOKOMO' => 'T',
	'SUMTER' => 'T',
	'GREATFALLS' => 'T',
	'RADCLIFF' => 'T',
	'CHATTANOOGA' => 'B',
	'BROWNSVILLE' => 'T',
	'OVERLANDPARK' => 'B',
	'TEMPE' => 'T',
	'ROCKFORD' => 'B',
	'BOISE' => 'B',
	'HUNTSVILLE' => 'B',
	'LITTLEROCK' => 'B',
	'AMARILLO' => 'B',
	'KNOXVILLE' => 'B',
	'SALTLAKECITY' => 'B',
	'JACKSON' => 'B',
	'GILBERTTOWN' => 'T',
	'KANSASCITY' => 'B',
	'IOWA' => 'S',
	'ILLINOIS' => 'S',
	'KANSAS' => 'S',
	'MINNESOTA' => 'S',
	'MISSOURI' => 'S',
	'NEBRASKA' => 'S',
	'OKLAHOMA' => 'S',
	'WISCONSIN' => 'S',
	'ALABAMA' => 'S',
	'ARKANSAS' => 'S',
	'KENTUCKY' => 'S',
	'LOUISIANA' => 'S',
	'MISSISSIPPI' => 'S',
	'TENNESSEE' => 'S',
	'TEXAS' => 'S',
	'NORTHDAKOTA' => 'S',
	'SOUTHDAKOTA' => 'S',
	'IDAHO' => 'S',
	'ARIZONA' => 'S',
	'NEWMEXICO' => 'S',
	'COLORADO' => 'S',
	'PUEBLO' => 'T',
	'UTAH' => 'S',
	'MONTANA' => 'S',
	'WYOMING' => 'S',
	'BIRMINGHAM' => 'B',
	'MOBILE' => 'B',
	'MONTGOMERY' => 'B',
	'DESMOINES' => 'B',
	'CHICAGO' => 'B',
	'LEXINGTON' => 'B',
	'LOUISVILLE' => 'B',
	'BATONROUGE' => 'B',
	'NEWORLEANS' => 'B',
	'SHREVEPORT' => 'B',
	'MINNEAPOLIS' => 'B',
	'STPAUL' => 'B',
	'KANSASCITYMO' => 'B',
	'SPRINGFIELDIL' => 'B',
	'LINCOLN' => 'B',
	'OMAHA' => 'B',
	'OKLAHOMACITY' => 'B',
	'TULSA' => 'B',
	'MEMPHIS' => 'B',
	'NASHVILLE' => 'B',
	'ARLINGTONVA' => 'B',
	'AUSTIN' => 'B',
	'CORPUSCHRISTI' => 'B',
	'DALLAS' => 'B',
	'GARLAND' => 'T',
	'HOUSTON' => 'B',
	'IRVING' => 'T',
	'LUBBOCK' => 'B',
	'PLANO' => 'T',
	'SANANTONIO' => 'B',
	'MADISON' => 'B',
	'MILWAUKEE' => 'B',
	'GLENDALE' => 'T',
	'MESA' => 'T',
	'PHOENIX' => 'B',
	'SCOTTSDALE' => 'T',
	'TUCSON' => 'B',
	'AURORA' => 'T',
	'COLORADOSPRINGS' => 'B',
	'DENVER' => 'B',
	'ALBUQUERQUE' => 'B',
	'SPRINGFIELDMO' => 'B',
	'WINSTONSALEM' => 'B',
	'JOLIET' => 'T',
	'GRANDEPRARIE' => 'T',
	'PASADENA' => 'T',
	'NAPERVILLE' => 'T',
	'SIOUXFALLS' => 'B',
	'PEORIA' => 'T',
	'FORTCOLLINS' => 'B',
	'CEDARRAPIDS' => 'B',
	'TOPEKA' => 'B',
	'ABILENE' => 'B',
	'CLARKSVILLE' => 'T',
	'LAFAYETTE' => 'T',
	'BEAUMONT' => 'T',
	'OLATHE' => 'T',
	'INDEPENDENCE' => 'B',
	'WESTMINSTER' => 'T',
	'ARVADA' => 'T',
	'PEUBLO' => 'T',
	'NORMAN' => 'T',
	'FLORIDA' => 'S',
	'GEORGIA' => 'S',
	'INDIANA' => 'S',
	'MICHIGAN' => 'S',
	'OHIO' => 'S',
	'MASSACHUSETTS' => 'S',
	'MARYLAND' => 'S',
	'NEWJERSEY' => 'S',
	'NEWYORK' => 'S',
	'PENNSYLVANIA' => 'S',
	'RHODEISLAND' => 'S',
	'NORTHCAROLINA' => 'S',
	'VIRGINIA' => 'S',
	'VIRGINIABEACH' => 'T',
	'SOUTHCAROLINA' => 'S',
	'MAINE' => 'S',
	'NEWHAMPSHIRE' => 'S',
	'VERMONT' => 'S',
	'CONNECTICUT' => 'S',
	'DELEWARE' => 'S',
	'WESTVIRGINIA' => 'S',
	'JACKSONVILLE' => 'B',
	'MIAMI' => 'B',
	'MIRAMAR' => 'T',
	'ORLANDO' => 'B',
	'TAMPA' => 'B',
	'ATLANTA' => 'B',
	'AUGUSTA' => 'B',
	'FORTWAYNE' => 'B',
	'INDIANAPOLIS' => 'B',
	'BOSTON' => 'B',
	'BALTIMORE' => 'B',
	'DETROIT' => 'B',
	'GRANDRAPIDS' => 'B',
	'CHARLOTTE' => 'B',
	'GREENSBORO' => 'B',
	'RALEIGH' => 'B',
	'JERSEYCITY' => 'B',
	'NEWARK' => 'B',
	'BUFFALO' => 'B',
	'NEWYORK' => 'B',
	'ROCHESTER' => 'B',
	'YONKERS' => 'T',
	'AKRON' => 'B',
	'CINCINNATI' => 'B',
	'CLEVELAND' => 'B',
	'COLUMBUS' => 'B',
	'TOLDEO' => 'B',
	'PHILADELPHIA' => 'B',
	'ARLINGTONVA' => 'T',
	'CHESAPEAKE' => 'T',
	'NORFOLK' => 'B',
	'RICHMOND' => 'B',
	'VIRGINABEACH' => 'T',
	'WASHINGTONDC' => 'B',
	'TALLAHASSEE' => 'B',
	'COLUMBUS' => 'T',
	'WORCESTER' => 'T',
	'SALEM' => 'B',
	'DAYTON' => 'B',
	'PROVIDENCE' => 'B',
	'NEWPORTNEWS' => 'T',
	'PEMBROKEPINES' => 'T',
	'SPRINGFIELDMA' => 'B',
	'BROOKLYN' => 'B',
	'PATERSON' => 'T',
	'HAMPTON' => 'T',
	'SYRACUSE' => 'B',
	'FTLAUDERDALE' => 'B',
	'HOLLYWOOD' => 'T',
	'CAPECORAL' => 'T`',
	'BRIDGEPORT' => 'B',
	'ALEXANDRIA' => 'B',
	'WARREN' => 'T',
	'PORTSTLUCIE' => 'T',
	'FAYETTEVILLE' => 'B',
	'POMPANOBEACH' => 'T',
	'SAVANNAH' => 'B',
	'STERLINGHEIGHTS' => 'T',
	'ELIZABETH' => 'T',
	'NEWHAVEN' => 'B',
	'HARTFORD' => 'B',
	'STAMFORD' => 'T',
	'FLINT' => 'T',
	'COLUMBIA' => 'B',
	'EVANSVILLE' => 'B',
	'LANSING' => 'B',
	'ANNARBOR' => 'T',
	'MANCHESTER' => 'B',
	'GAINSVILLE' => 'B',
	'WATERBURY' => 'B',
	'ALLENTOWN' => 'T',
	'CHARLESTON' => 'B',
	'CARY' => 'T',
	'DALTON' => 'T',
	'SOUTHBEND' => 'B',
	'LOWELL' => 'T',
	'ERIE' => 'B',
	'GREENBAY' => 'B',
	'PORTSMOUTH' => 'T'
	
	
	);

	$locationSearch = null;
	$stringInCode = null;
	foreach($trackingCodeSearchArr as $thisStringInCode => $thisLocationSearch){
		if(preg_match("/$thisStringInCode/i", $trackingCodeStr)){
			$locationSearch = $thisLocationSearch;
			$stringInCode = $thisStringInCode;
			break;
		}
	}
	
	// Can't find a match in the tracking code.
	if(empty($locationSearch)){
		
		// Return "ALL" for the geo location if we can't find the a city or a territory in the code.
		if(!preg_match("/Cty/i", $trackingCodeStr) && !preg_match("/_State/i", $trackingCodeStr) && !preg_match("/\-State/i", $trackingCodeStr) && !preg_match("/Eastern/i", $trackingCodeStr) && !preg_match("/Pacific/i", $trackingCodeStr) && !preg_match("/Central/i", $trackingCodeStr))
			return $trackingCodeStr . "^all^";
			
		print "<br><br><u>No Location Found for $locationSearch </u>";
			
		return $trackingCodeStr;
	}
		
		
	if(!array_key_exists($locationSearch, $replaceZoneNumber)){
		exit("-------------------   Can not find a Replacement Zone from the Location Search -------------- : $locationSearch");
	}
	
	// g-geo_sCty_Z4-3-em-bc_cheap
	// Use ^ symbols to make it easy to locate the location section.
	$codeReplacement = "^geo_";

	if($replaceLocationType[$locationSearch] == "S")
		$codeReplacement .= "state_Z";
	else if($replaceLocationType[$locationSearch] == "T")
		$codeReplacement .= "tCty_Z";
	else if($replaceLocationType[$locationSearch] == "B")
		$codeReplacement .= "bCty_Z";

	$codeReplacement .= $replaceZoneNumber[$locationSearch] . "^";
	
	$trackingCodeStr = preg_replace("/$stringInCode/i", $codeReplacement, $trackingCodeStr);
	
	return $trackingCodeStr;
}








